In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import keras as ks

from sklearn.datasets import load_iris, load_digits, fetch_20newsgroups_vectorized
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

from keras.datasets import mnist, fashion_mnist
from keras.layers import Dense, Conv2D, Dropout, Flatten, MaxPooling2D, LSTM, Embedding
from keras.utils import np_utils

import matplotlib.pyplot as plt

2022-05-10 14:10:42.413477: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/kaygun/local/lib
2022-05-10 14:10:42.413536: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


# Standard Neural Network

In [2]:
iris = load_iris()
x_iris = iris['data']
y_iris = iris['target']

labeler = LabelBinarizer()
y = labeler.fit_transform(y_iris)

x_train, x_test, y_train, y_test = train_test_split(x_iris, y)

In [3]:
y_train

array([[0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [ ]:
model = ks.models.Sequential()

model.add(ks.layers.Dense(64, activation='relu', input_dim=4))
model.add(ks.layers.Dense(3,activation='sigmoid'))

In [5]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['binary_accuracy'])

model.fit(x_train,y_train,epochs=10,batch_size=100)

Epoch 1/10
2/2 [==============================] - 0s 2ms/step - loss: 0.2363 - binary_accuracy: 0.8810
Epoch 2/10
2/2 [==============================] - 0s 3ms/step - loss: 0.2355 - binary_accuracy: 0.8810
Epoch 3/10
2/2 [==============================] - 0s 2ms/step - loss: 0.2360 - binary_accuracy: 0.8720
Epoch 4/10
2/2 [==============================] - 0s 3ms/step - loss: 0.2369 - binary_accuracy: 0.8839
Epoch 5/10
2/2 [==============================] - 0s 2ms/step - loss: 0.2379 - binary_accuracy: 0.9018
Epoch 6/10
2/2 [==============================] - 0s 3ms/step - loss: 0.2378 - binary_accuracy: 0.9077
Epoch 7/10
2/2 [==============================] - 0s 3ms/step - loss: 0.2360 - binary_accuracy: 0.8988
Epoch 8/10
2/2 [==============================] - 0s 2ms/step - loss: 0.2344 - binary_accuracy: 0.8869
Epoch 9/10
2/2 [==============================] - 0s 3ms/step - loss: 0.2327 - binary_accuracy: 0.8810
Epoch 10/10
2/2 [==============================] - 0s 2ms/step - loss: 0.

In [6]:
y_pred = model.predict(x_test)
yy_pred = np.argmax(y_pred,axis=1)
yy_test = np.argmax(y_test,axis=1)

print(accuracy_score(yy_test,yy_pred))
confusion_matrix(yy_test,yy_pred)

1.0


array([[13,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 12]])

# Convolutional Neural Networks

In [7]:
digits = load_digits()
x_digits = digits['data']
y_digits = digits['target']

In [8]:
labeler = LabelBinarizer()

yy_digits = labeler.fit_transform(y_digits)
xx_digits = x_digits.reshape(1797,8,8,1)

x_train, x_test, y_train, y_test = train_test_split(xx_digits, yy_digits)

In [9]:
model = ks.models.Sequential()

model.add(Conv2D(64, (3, 2), padding="same", activation='relu', input_shape=(8,8,1)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation = 'relu'))
model.add(Dense(10, activation = 'softmax'))

In [10]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['binary_accuracy'])

model.fit(x_train, y_train, batch_size=64, epochs=50)

Epoch 1/50
22/22 [==============================] - 0s 4ms/step - loss: 0.3030 - binary_accuracy: 0.9151
Epoch 2/50
22/22 [==============================] - 0s 4ms/step - loss: 0.1120 - binary_accuracy: 0.9747
Epoch 3/50
22/22 [==============================] - 0s 4ms/step - loss: 0.0697 - binary_accuracy: 0.9863
Epoch 4/50
22/22 [==============================] - 0s 4ms/step - loss: 0.0484 - binary_accuracy: 0.9924
Epoch 5/50
22/22 [==============================] - 0s 4ms/step - loss: 0.0410 - binary_accuracy: 0.9930
Epoch 6/50
22/22 [==============================] - 0s 4ms/step - loss: 0.0355 - binary_accuracy: 0.9939
Epoch 7/50
22/22 [==============================] - 0s 4ms/step - loss: 0.0286 - binary_accuracy: 0.9962
Epoch 8/50
22/22 [==============================] - 0s 4ms/step - loss: 0.0233 - binary_accuracy: 0.9973
Epoch 9/50
22/22 [==============================] - 0s 4ms/step - loss: 0.0252 - binary_accuracy: 0.9966
Epoch 10/50
22/22 [==============================] - 0s

In [11]:
y_pred = model.predict(x_test)
yy_pred = np.argmax(y_pred,axis=1)
yy_test = np.argmax(y_test,axis=1)

print(accuracy_score(yy_test,yy_pred))
confusion_matrix(yy_test,yy_pred)

0.9866666666666667


array([[38,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 54,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 43,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 46,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 36,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 51,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 41,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 41,  0,  0],
       [ 0,  1,  0,  2,  0,  1,  0,  0, 50,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  1, 44]])

# Recurrent Neural Networks

In [12]:
newsgroups = fetch_20newsgroups_vectorized()

In [15]:
x_news = newsgroups['data'].toarray()
y_news = newsgroups['target']

In [16]:
labeler = LabelBinarizer()
yy_news = labeler.fit_transform(y_news)

x_train, x_test, y_train, y_test = train_test_split(x_news,yy_news)
x_train.shape

(8485, 130107)

In [17]:
model = ks.Sequential()

model.add(Embedding(input_dim=x_train.shape[1], output_dim=128))
model.add(Dense(128,activation='relu'))
model.add(Dense(20,activation='softmax'))

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, None, 128)         16653696  
                                                                 
 dense_6 (Dense)             (None, None, 128)         16512     
                                                                 
 dense_7 (Dense)             (None, None, 20)          2580      
                                                                 
Total params: 16,672,788
Trainable params: 16,672,788
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['binary_accuracy'])

model.fit(x_train,y_train,epochs=300,batch_size=100)

2022-05-10 14:40:51.770673: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 4415831580 exceeds 10% of free system memory.


Epoch 1/300


ValueError: in user code:

    File "/home/kaygun/.local/lib/python3.10/site-packages/keras/engine/training.py", line 1021, in train_function  *
        return step_function(self, iterator)
    File "/home/kaygun/.local/lib/python3.10/site-packages/keras/engine/training.py", line 1010, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/kaygun/.local/lib/python3.10/site-packages/keras/engine/training.py", line 1000, in run_step  **
        outputs = model.train_step(data)
    File "/home/kaygun/.local/lib/python3.10/site-packages/keras/engine/training.py", line 860, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/home/kaygun/.local/lib/python3.10/site-packages/keras/engine/training.py", line 918, in compute_loss
        return self.compiled_loss(
    File "/home/kaygun/.local/lib/python3.10/site-packages/keras/engine/compile_utils.py", line 201, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/home/kaygun/.local/lib/python3.10/site-packages/keras/losses.py", line 141, in __call__
        losses = call_fn(y_true, y_pred)
    File "/home/kaygun/.local/lib/python3.10/site-packages/keras/losses.py", line 245, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/home/kaygun/.local/lib/python3.10/site-packages/keras/losses.py", line 1932, in binary_crossentropy
        backend.binary_crossentropy(y_true, y_pred, from_logits=from_logits),
    File "/home/kaygun/.local/lib/python3.10/site-packages/keras/backend.py", line 5247, in binary_crossentropy
        return tf.nn.sigmoid_cross_entropy_with_logits(labels=target, logits=output)

    ValueError: `logits` and `labels` must have the same shape, received ((None, 130107, 20) vs (None, 20)).


In [72]:
x_train.toarray().astype(np.float16)

KeyboardInterrupt: 